-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 20:26:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FlashcardDeck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FlashcardDeck` (
  `idFlashcardDeck` INT NOT NULL,
  `deckName` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idFlashcardDeck`, `User_idUser`),
  UNIQUE INDEX `idFlashcardDeck_UNIQUE` (`idFlashcardDeck` ASC) VISIBLE,
  UNIQUE INDEX `FlashcardDeckName_UNIQUE` (`deckName` ASC) VISIBLE,
  INDEX `fk_FlashcardDeck_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_FlashcardDeck_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FlashcardType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FlashcardType` (
  `idFlashcardType` INT NOT NULL,
  `typeName` VARCHAR(45) NOT NULL,
  `FlashcardDeck_idFlashcardDeck` INT NOT NULL,
  PRIMARY KEY (`idFlashcardType`, `FlashcardDeck_idFlashcardDeck`),
  UNIQUE INDEX `idFlashcardType_UNIQUE` (`idFlashcardType` ASC) VISIBLE,
  UNIQUE INDEX `FlashcardTypeName_UNIQUE` (`typeName` ASC) VISIBLE,
  INDEX `fk_FlashcardType_FlashcardDeck_idx` (`FlashcardDeck_idFlashcardDeck` ASC) VISIBLE,
  CONSTRAINT `fk_FlashcardType_FlashcardDeck`
    FOREIGN KEY (`FlashcardDeck_idFlashcardDeck`)
    REFERENCES `mydb`.`FlashcardDeck` (`idFlashcardDeck`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JapaneseFlashcard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JapaneseFlashcard` (
  `idJapaneseFlashcard` INT NOT NULL,
  `japaneseText` VARCHAR(500) NULL,
  `readingText` VARCHAR(500) NULL,
  `meaningText` VARCHAR(500) NULL,
  `englishText` VARCHAR(500) NULL,
  `nextReviewDate` DATETIME NULL,
  `FlashcardType_idFlashcardType` INT NOT NULL,
  `FlashcardType_FlashcardDeck_idFlashcardDeck` INT NOT NULL,
  PRIMARY KEY (`idJapaneseFlashcard`, `FlashcardType_idFlashcardType`, `FlashcardType_FlashcardDeck_idFlashcardDeck`),
  UNIQUE INDEX `idJapaneseFlashcard_UNIQUE` (`idJapaneseFlashcard` ASC) VISIBLE,
  INDEX `fk_JapaneseFlashcard_FlashcardType1_idx` (`FlashcardType_idFlashcardType` ASC, `FlashcardType_FlashcardDeck_idFlashcardDeck` ASC) VISIBLE,
  CONSTRAINT `fk_JapaneseFlashcard_FlashcardType1`
    FOREIGN KEY (`FlashcardType_idFlashcardType` , `FlashcardType_FlashcardDeck_idFlashcardDeck`)
    REFERENCES `mydb`.`FlashcardType` (`idFlashcardType` , `FlashcardDeck_idFlashcardDeck`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
